### ISSUE TITLE
Can't mute ACRE spectators when in Pabst Spectator

### ISSUE THREAD

**Issue by JonBons** [zerithsmash/bwmf#20]
Due to the UI handling keyDown/keyUp actions I don't think ACRE2 is getting passed the Mute Spectator binding.

I could make a mute spect button or have it get the ACRE2 key binding and handle it.

**Comment by JonBons** [comment]
Mozaik informed me that you can hit Esc (and it will close the spectator ui for a couple secs) and then you can hit the keybind really quickly but its a workaround.

**Comment by Waffle-SS** [comment]
Have you tried adding an eventhandler to the spectator display itself?

**Comment by JonBons** [comment]
The spectator display already handles keyDown/keyUp events.

I resolved this via using ["ACRE2","HeadSet"] call cba_fnc_getKeybind to get the details about what the controls are to activate and then in the keyUp event I call the keyUp function that cba_fnc_getKeybind returned if proper keys where pressed.

**Comment by PabstMirror** [comment]
Should be fixed with: 7ba75dae6bf58ba8c7ff66b1582e8bb2ffd5d730
