### ISSUE TITLE
Gear redundancy

### ISSUE THREAD

**Issue by zerithsmash** [zerithsmash/bwmf#23]
Recently we added a check that if gear was not found for a unit the gear would default to that unit's config gear to better combat situations where mods were removed. This appears to pose a problem with ALiVE in that we don't have as easy control over what units are spawned in. It may be better to consider defaulting all units to a specific loadout per side if their class/gear is not found. We could use vanilla gear for this case if needed.

**Comment by Waffle-SS** [comment]
We should probably learn more about how to use ALiVE before we start making loadouts for every unit type.It would be much better to figure out how to customize what units ALiVE spawns.

**Comment by zerithsmash** [comment]
I'm not suggesting making loadouts for every unit type. I'm suggesting if a unit type doesn't have a loadout defined then it will default to a regular rifleman. AACO already halfway implemented something for testing, but it means using a "spawn" vs "call".

**Comment by PabstMirror** [comment]
There are two separate issues

* No loadouts for non-defined units.  ACCO has an implantation that should work great on this.

* The ACRE/ALIVE thing? havne't seen this issue, don't know much about it.  Right now, I'm not real happy with ACOO's spawn stuff, but I haven't even seen the issue reproduced so who knows.

**Comment by zerithsmash** [comment]
The only problem from tonight with it is that it would take upwards to a minute sometimes for the AI to get the right gear. Not sure if that's something that can be fixed/changed though. But I do agree I would rather find some ALiVE side solutions to some of this.

**Comment by AACO** [comment]
My crap workaround no longer uses spawn ref: https://github.com/AACO

**Comment by zerithsmash** [comment]
This was implemented and will be commented out by default. Coop mission makers will need to be aware of this to maintain gear consistency.
