### ISSUE TITLE
Second Headless Client 

### ISSUE THREAD

**Issue by zerithsmash** [zerithsmash/bwmf#31]
Future proof mission.sqm to be setup for a second HC for COOPs with ALiVE

**Comment by zerithsmash** [comment]
Implementation didn't seem too bad but it produced funky results. ie - Units moonwalking or major desync between players.

**Comment by zerithsmash** [comment]
A second HC works fine w/ something like a zeus-based mission. Not really sure if it's worth it though. 1 HC handles those types of missions fine.

**Comment by AACO** [comment]
With our current memory restrictions, it seems like a second HC is a risk to server stability. This can probably be closed out (we can revisit this is we ever change/get more serious hardware).

**Comment by MikeMatrix** [comment]
Maybe tag it as Backlog

**Comment by AACO** [comment]
@MikeMatrix acting like we have a backlog

**Comment by MikeMatrix** [comment]
@AACO acting like we can't use a tag to track things that we might want to revisit at an unspecified later time :shipit:

**Comment by AACO** [comment]
(we can, but I don't have that power)

**Comment by AACO** [comment]
(also we dropped alive, closing this until we have better hardware)
