### ISSUE TITLE
Implement 1Tac's Respawn UI?

### ISSUE THREAD

**Issue by zerithsmash** [zerithsmash/bwmf#34]
I've been wanting to do this for ages. Snipper at 1tac has a respawn UI for admins so that they can dynamically respawn dead players for reinforcements. The code can be found here. I don't know what work would need to be done to implement it into our framework or update it, but I'm just throwing it out there to see if anybody is interested in taking a look at it.

https://github.com/Sniperhid/1Tac-F3/tree/master/f/respawn

**Comment by zerithsmash** [comment]
I've been notified that 1.52 did break this.

**Comment by zerithsmash** [comment]
This was fixed.

**Comment by AACO** [comment]
In progress in the respawn branch, will close when branch is merged

**Comment by AACO** [comment]
Donzo
